import type { Metadata } from "next";
import { Outfit } from "next/font/google";

const outfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfitFont.variable} font-outfitFont bg-gradient-to-r from-gray-900 to-gray-800  flex h-lvh`}
      >
        {children}
      </body>
    </html>
  );
}
